name: gps_field_assist_mobile
description: Application mobile pour GPS Field Assist
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  image_picker: ^1.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  telephony:
    path: third_party/telephony
  syncfusion_flutter_pdfviewer: ^32.2.7
  flutter_launcher_icons: ^0.14.4
  path_provider: ^2.1.5
  webview_flutter: ^4.10.0
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/logo.png"
flutter:
  uses-material-design: true
  
  assets:
    - assets/logoTunav.png
    - assets/logoTunavBlanc.png
    - assets/fond tunav.jpg
    - assets/logo_ooredoo.png
    - assets/logo_orange.png
    - assets/logo_telecom.png
    - assets/MT02S-200.jpg
    - assets/ICON_CHATBOT.png
    - assets/icone.gif
    - assets/ET7.jpeg
    - assets/FM4200_v1.92.jpeg
    - assets/FM5300_ v3.4.jpeg
    - assets/FMA120_v1.17.jpeg
    - assets/GT06N.jpeg
    - assets/GT06N_autre.jpeg
    - assets/gv300can-gps.jpg.jpeg
    - assets/icon/
